ERROR 2022-08-20 20:34:45,027 root  division by zero
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\Logging project\test3.py", line 21, in divide
    div=a/b
ZeroDivisionError: division by zero
INFO 2022-08-20 20:36:36,359 root  stored no entered by user is 3 and 4
INFO 2022-08-20 20:36:36,360 root  we are into try block of function
INFO 2022-08-20 20:36:36,360 root  we have completed divison operation
INFO 2022-08-20 20:36:36,361 root  The return of code is 0.75
INFO 2022-08-20 20:37:02,003 root  stored no entered by user is 2 and 0
INFO 2022-08-20 20:37:02,004 root  we are into try block of function
ERROR 2022-08-20 20:37:02,004 root  division by zero
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\Logging project\test3.py", line 21, in divide
    div=a/b
ZeroDivisionError: division by zero
